name: Android Builds

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  build:
    name: Build Example
    runs-on: ubuntu-latest

    steps:
    - uses: vgaidarji/android-github-actions-build@v1.0.1
    - with:
        args: "./gradlew :example:assembleDebug"
