name: Android Builds

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  build:
    name: Build Example
    runs-on: ubuntu-latest
    run: ./gradlew :example:assembleDebug
